name: "Manual Execution for All Organization Repositories"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
        required: false
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
        required: false
      issue_title:
        description: "Issue title"
        required: false
      period_split_unit:
        description: "Unit for time segmentation"
        required: false
        default: "months"
        type: choice
        options:
          - years
          - quarters
          - months
          - none
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.IM_FUNDING_ORG_REPO_TOKEN }}
          LABELS: "PR Activity Report"
          ORGANIZATIONS: "im-funding"
          GITHUB_OWNER_FOR_ISSUE: "michael-guthrie"
          GITHUB_REPO_FOR_ISSUE: "github-actions-sandbox"
          CORE_HOURS_START: "2:00"
          CORE_HOURS_END: "18:00"
          TIMEZONE: "america/denver"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
          ISSUE_TITLE: ${{ inputs.issue_title }}
          PERIOD_SPLIT_UNIT: ${{ inputs.period_split_unit }}