name: "Manual Execution for All Organization Repositories"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
        required: false
      report_date_end:
        description: "Report date end(d/MM/yyyy)"
        required: false
      issue_title:
        description: "Issue title"
        required: false
      period_split_unit:
        description: "Unit for time segmentation"
        required: false
        default: "months"
        type: choice
        options:
          - years
          - quarters
          - months
          - none
jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.IM_ORG_REPO_TOKEN }}
          LABELS: "PR Activity Report"
          ORGANIZATIONS: "im-funding,im-platform,im-practices"
          # GITHUB_OWNERS_REPOS: "im-funding/allocation-manager,im-funding/BenefitsAccounts-Gateway-Service,im-funding/client-configuration-graphql-api,im-funding/client-configuration-team,im-funding/client-data-azure-infrastructure,im-funding/client-guides-azure-functions,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/,im-funding/"
          GITHUB_OWNER_FOR_ISSUE: "michael-guthrie"
          GITHUB_REPO_FOR_ISSUE: "github-actions-sandbox"
          SHOW_USERS: "AdityaRayWTW,brentAaronPatterson,BretPehrsonWTW,Dshoupe,gordke,heatherjnelson,jasonsroka1,JoaquinPretell92,JosueNinolibre,LUNA56144,ManuelFerna,mgoicochea-wtwco,michael-guthrie,RaviWTW,RuntimeRascal,SopanChaudhariWTW,Suyalur"
          CORE_HOURS_START: "2:00"
          CORE_HOURS_END: "18:00"
          TIMEZONE: "america/denver"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
          ISSUE_TITLE: ${{ inputs.issue_title }}
          PERIOD_SPLIT_UNIT: ${{ inputs.period_split_unit }}