name: Workflow Dispatch Test

on:
  workflow_dispatch:
    inputs:
      fruit:
        description: Select a fruit
        required: true
        type: choice
        options:
          - apple
          - banana
          - watermelon

env:
  FRUIT_SELECTION: ${{ github.event.inputs.fruit }}
  FRUIT_ABBREVIATION: ${{ github.event.inputs.fruit == 'apple' && 'ap' || github.event.inputs.fruit == 'banana' && 'bn' || 'wm' }}
  CP_FRUIT_SELECTION: ${{ github.event.client_payload.fruit }}
  CP_FRUIT_ABBREVIATION: ${{ github.event.client_payload.fruit == 'apple' && 'ap' || github.event.client_payload.fruit == 'banana' && 'bn' || 'wm' }}
  COALESCE_FRUIT_SELECTION: ${{ github.event.client_payload.fruit || github.event.inputs.fruit }}
  COALESCE_FRUIT_ABBREVIATION: ${{ (github.event.client_payload.fruit || github.event.inputs.fruit) == 'apple' && 'ap' || (github.event.client_payload.fruit || github.event.inputs.fruit) == 'banana' && 'bn' || 'wm' }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "You chose ${{ env.FRUIT_SELECTION }} which we abbreviated as ${{ env.FRUIT_ABBREVIATION }}"
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "github.event.inputs values (${{ env.FRUIT_SELECTION }}, ${{ env.FRUIT_ABBREVIATION }})"
          echo "github.event.client_payload values (${{ env.CP_FRUIT_SELECTION }}, ${{ env.CP_FRUIT_ABBREVIATION }})"
          echo "coalesced values (${{ env.COALESCE_FRUIT_SELECTION }}, ${{ env.COALESCE_FRUIT_ABBREVIATION }})"
